//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDogovorami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int ID { get; set; }
        public decimal Price { get; set; }
        public decimal Avance { get; set; }
        public Nullable<decimal> First_part { get; set; }
        public Nullable<decimal> Second_part { get; set; }
        public Nullable<decimal> Third_part { get; set; }
        public Nullable<decimal> Fourth_part { get; set; }
        public System.DateTime Avance_date { get; set; }
        public Nullable<System.DateTime> First_part_date { get; set; }
        public Nullable<System.DateTime> Second_part_date { get; set; }
        public Nullable<System.DateTime> Fourth_part_date { get; set; }
        public int Client_id { get; set; }
        public int Manager_id { get; set; }
        public int Type_id { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Types Types { get; set; }
    }
}
