//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDogovorami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.Parts = new HashSet<Parts>();
            this.Payded = new HashSet<Payded>();
        }
    
        public int ID { get; set; }
        public string Price { get; set; }
        public string Avance { get; set; }
        public System.DateTime Avance_date { get; set; }
        public Nullable<int> Client_id { get; set; }
        public Nullable<int> Manager_id { get; set; }
        public Nullable<int> Type_id { get; set; }
        public Nullable<int> Stasus_id { get; set; }
        public Nullable<int> Currency_id { get; set; }
        public Nullable<int> Parts_count { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parts> Parts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payded> Payded { get; set; }
    }
}
