//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDogovorami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.Parts = new HashSet<Parts>();
            this.Payded1 = new HashSet<Payded>();
        }
    
        public int ID { get; set; }
        public int Price { get; set; }
        public int Parts_count { get; set; }
        public int Avance { get; set; }
        public System.DateTime Avance_date { get; set; }
        public int Client_id { get; set; }
        public int Manager_id { get; set; }
        public int Type_id { get; set; }
        public int Stasus_id { get; set; }
        public int Currency_id { get; set; }
        public Nullable<double> Shtraf_procent { get; set; }
        public Nullable<double> Shtraf { get; set; }
        public Nullable<double> Avance_shtraf { get; set; }
        public Nullable<double> Payded { get; set; }
        public Nullable<double> FP_Peni { get; set; }
        public Nullable<double> SP_Peni { get; set; }
        public Nullable<double> THP_Peni { get; set; }
        public Nullable<double> FOURP_Peni { get; set; }
        public Nullable<double> Dolg { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parts> Parts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payded> Payded1 { get; set; }
    }
}
